### ISSUE TITLE
Issue on placeolder parsing

### ISSUE THREAD

**Issue by WarnDa** [Frcsty/FrozenJoin#28]
I'm using FrozenJoin 2.3.0 on paper 1.16.5, and I made a custom javascript that check for player permission to display a custom rank when player connect/disconnect.

When he connect it works fine, but when he disconnects it doesn't parse it (seems an issue where the player is already offline when it parses the javascript, so it can't detect his permission.)

It would be possible to save in cache or parse the placeholder before the player is offline ?

**Comment by BlitzOffline** [comment]
There is already plans of adding placeholder caching. this will cache the placeholder every # milliseconds. There is no actual way of parsing the placeholder before the player is offline as the event is fired 1 tick after the disconnect.

Placing this link here to remember lol: https://discord.com/channels/164280494874165248/695431668944732270/930805808424419329 (my discussion with frosty. not related)

**Comment by WarnDa** [comment]
Hello,

Any news on that ? :(

**Comment by BlitzOffline** [comment]
Hello. I've noticed you closed this. I completely forgot about this to be honest. When this was opened I was very busy and then just forgot. I took some time today to add a cache however. I am going to test it some more and maybe make a small spigot release tomorrow. I can also give you a development build before if you want.

**Comment by WarnDa** [comment]
Hello,

I did another way to fix this issue, by manually write every prefix, instead of using a placeholder :)
That's why I closed this, but nice for other people then !
