### ISSUE TITLE
Possible to support relational placeholders?

### ISSUE THREAD

**Issue by ghost** [Frcsty/FrozenJoin#35]
Basically what the title says, for example, placeholders like Factions, `%rel_factionsuuid_relation_color%`

**Comment by BlitzOffline** [comment]
I'm assuming you want this for Broadcast/Global actions since those are the only actions where multiple players are avilable. I will look into it.

**Comment by BlitzOffline** [comment]
Hi @michael-b-jordan.

Any chance you would have the time and resources to test a build which contains the changes you've requested? The build is attached to this comment.

The changes from this build are:
- Relational placeholders caching (see config.yml#placeholder-cache.relational-placeholders)
- Relational placeholders support in the following actions: ACTIONBARBROADCAST, AUDIENCEBROADCAST, BROADCAST, CENTERBROADCAST, JSONBROADCAST, TITLEBROADCAST, PERSISTENTACTIONBARBROADCAST.

Other changes that this build contains when compared to the spigot release are:
- PERSISTENTACTIONBARMESSAGE and PERSISTENTACTIONBARBROADCAST actions
	- The way they work: `[PERSISTENTACTIONBARBROADCAST] <time>;<message>` - time is in seconds. These actions allows action bar messages to be sent with a set duration. The simple action bar action sends the messages with a 3 second duration.    

[FrozenJoin-2.3.2-builds-relational-placeholders.zip](https://github.com/Frcsty/FrozenJoin/files/11910609/FrozenJoin-2.3.2-builds-relational-placeholders.zip)

**Comment by ghost** [comment]
Sure, appreciate the fast response, relational placeholders and persistentaction are both working perfectly, thanks.
