### ISSUE TITLE
The Converter Dont Work

### ISSUE THREAD

**Issue by TheCiROMG** [Frcsty/FrozenJoin#6]
Basically, I do everything that it asks for, put the generate command, put the file in the folder itself, hit start ... but when start it says that the same folder does not exist BUT IT IS CREATED AND WITH THE FILE INSIDE

![image](https://user-images.githubusercontent.com/61605643/91664715-63160380-eac7-11ea-94fb-93952756de37.png)

**Comment by Frcsty** [comment]
Tested and debugged multiple times, and it seems to work as intended.
