### ISSUE TITLE
PAPI on player leave

### ISSUE THREAD

**Issue by mrsqueak11806** [Frcsty/FrozenJoin#7]
If a player leaves the server the leave message doesn't include the name of the player when %essentials_nick% is used in the leave message.

**Comment by BlitzOffline** [comment]
I'm afraid there's not a lot that can be done about this since the player quit event is called after the player has left.

**Comment by Frcsty** [comment]
Don't believe there's a simple fix to this, will look into adding a cacheable placeholder to counter that.
