### ISSUE TITLE
[TITLEMESSAGE] Doesn't display correctly on server join. 2.1.4

### ISSUE THREAD

**Issue by mrsqueak11806** [Frcsty/FrozenJoin#8]
ormats:
  default:
    priority: 1
    type: 'NORMAL'
    join:
      - '[BROADCAST] &8[&a+&8] &6%vault_prefix% &6%essentials_nickname%'
      - '[TITLEMESSAGE] Welcome to CompetitorsPC Mine&7craft;20;80;20'
      - '[ACTIONBARBROADCAST] &6%vault_prefix% &6%essentials_nickname% &6is online'
      #- '[TITLEMESSAGE] &6Welcome to &cCompetitorsPC &2Mine&7craft;20;80;20'
    quit:
      - '[BROADCAST] &8[&c-&8] &6%vault_prefix% &6%essentials_nickname%'
      - '[ACTIONBARBROADCAST] &6%vault_prefix% &6%essentials_nickname% &6went offline'
    permission: 'frozenjoin.default'
![2020-09-24_05 17 42](https://user-images.githubusercontent.com/71041998/94133235-07206f80-fe26-11ea-822b-72bd1a107adb.png)

**Comment by BlitzOffline** [comment]
This was fixed in #13 

@Starmism please close. Thank you!
